<?php

namespace ContainerVRzRzSh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H59uUJxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.H59uUJx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.H59uUJx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'rolesUsuario' => ['privates', '.errored..service_locator.H59uUJx.App\\Entity\\RolesUsuario', NULL, 'Cannot autowire service ".service_locator.H59uUJx": it needs an instance of "App\\Entity\\RolesUsuario" but this type has been excluded in "config/services.yaml".'],
        ], [
            'rolesUsuario' => 'App\\Entity\\RolesUsuario',
        ]);
    }
}
