<?php

namespace ContainerWYjNqML;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D4qBJN9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d4qBJN9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d4qBJN9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'juego' => ['privates', '.errored..service_locator.d4qBJN9.App\\Entity\\Juego', NULL, 'Cannot autowire service ".service_locator.d4qBJN9": it needs an instance of "App\\Entity\\Juego" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'juego' => 'App\\Entity\\Juego',
        ]);
    }
}
