<?php

namespace ContainerWYjNqML;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1bnhOgbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1bnhOgb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1bnhOgb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'rolesUsuarioRepository' => ['privates', 'App\\Repository\\RolesUsuarioRepository', 'getRolesUsuarioRepositoryService', true],
        ], [
            'rolesUsuarioRepository' => 'App\\Repository\\RolesUsuarioRepository',
        ]);
    }
}
