<?php

namespace ContainerWYjNqML;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRolesUsuario2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.uCgzVkc.App\Entity\RolesUsuario' shared service.
     *
     * @return \App\Entity\RolesUsuario
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.uCgzVkc": it needs an instance of "App\\Entity\\RolesUsuario" but this type has been excluded in "config/services.yaml".');
    }
}
