<?php

namespace ContainerH6DhMCD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VbbOKKLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VbbOKKL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VbbOKKL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'generoRepository' => ['privates', 'App\\Repository\\GeneroRepository', 'getGeneroRepositoryService', true],
        ], [
            'generoRepository' => 'App\\Repository\\GeneroRepository',
        ]);
    }
}
