<?php

namespace ContainerH6DhMCD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_65ugF8sService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.65ugF8s' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.65ugF8s'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'genero' => ['privates', '.errored..service_locator.65ugF8s.App\\Entity\\Genero', NULL, 'Cannot autowire service ".service_locator.65ugF8s": it needs an instance of "App\\Entity\\Genero" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'genero' => 'App\\Entity\\Genero',
        ]);
    }
}
