<?php

namespace ContainerQJu6ESW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZjjydGRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zjjydGR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zjjydGR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'usuario' => ['privates', '.errored..service_locator.zjjydGR.App\\Entity\\Usuario', NULL, 'Cannot autowire service ".service_locator.zjjydGR": it needs an instance of "App\\Entity\\Usuario" but this type has been excluded in "config/services.yaml".'],
        ], [
            'usuario' => 'App\\Entity\\Usuario',
        ]);
    }
}
