<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW2h2nzZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW2h2nzZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW2h2nzZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW2h2nzZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW2h2nzZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'W2h2nzZ',
    'container.build_id' => '7b017af1',
    'container.build_time' => 1707382668,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW2h2nzZ');
