<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQJu6ESW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQJu6ESW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQJu6ESW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQJu6ESW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQJu6ESW\App_KernelDevDebugContainer([
    'container.build_hash' => 'QJu6ESW',
    'container.build_id' => 'cac3550c',
    'container.build_time' => 1707214952,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQJu6ESW');
