<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWYjNqML\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWYjNqML/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWYjNqML.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWYjNqML\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWYjNqML\App_KernelDevDebugContainer([
    'container.build_hash' => 'WYjNqML',
    'container.build_id' => 'a0b66dee',
    'container.build_time' => 1707303820,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWYjNqML');
